# Generated by Django 3.0.5 on 2020-06-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DNA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna', models.CharField(max_length=200)),
                ('isMutant', models.BooleanField()),
                ('dateLastRequest', models.DateField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Test2',
        ),
    ]
